### ISSUE TITLE
Rewrite Router.watch method with a callback

### ISSUE THREAD

**Issue by bendrucker** [bendrucker/sour#10]
Eliminate `state.watching` as the channel for booting the router. Instead manually "watch" by running `onPath` with a callback. `var unwatch = Router.watch(state, onReady)`. 

See https://github.com/bendrucker/sour/pull/3#issuecomment-220424516
cc @chrisinajar

**Comment by chrisinajar** [comment]
ACK ACK ACK ACK ACK ACK ACK ACK ACK ACK ACK ACK ACK ACK
