### ISSUE TITLE
Allow an array of paths to be passed into Sour.route

### ISSUE THREAD

**Issue by ajoslin** [bendrucker/sour#8]
See https://github.com/bendrucker/tafel/pull/1

I'd like to do the following:

```
Router.route(router, {
  path: [
    '/app',
    '/app/:listId/:detailId'
  ],
  // ... other args here
})
```

This would match either of the above urls.

As far as I can tell in looking at routington, there's no way to define two optional parameters.

If you merge the tafel PR, I can open a PR here with unit tests for multiple paths.

**Comment by bendrucker** [comment]
Merged

**Comment by ajoslin** [comment]
#9
